# Generated by Django 4.2.7 on 2023-12-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilletTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pole/billets')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('DDN', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('gare', models.CharField(blank=True, max_length=500, null=True)),
                ('carte', models.CharField(blank=True, max_length=50, null=True)),
                ('fin_validite', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('pf', models.BooleanField(default=True)),
                ('ph', models.BooleanField(default=False)),
            ],
        ),
    ]
