# Generated by Django 4.2.7 on 2023-12-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BilletTrain',
            new_name='Billet',
        ),
    ]
