# Generated by Django 4.2.7 on 2023-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0002_rename_billettrain_billet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billet',
        ),
        migrations.AlterField(
            model_name='personne',
            name='pf',
            field=models.BooleanField(default=False),
        ),
    ]
