# Generated by Django 4.2.7 on 2024-02-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0003_delete_billet_alter_personne_pf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=200, null=True)),
                ('definition', models.CharField(max_length=600, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('video', models.URLField(null=True)),
            ],
        ),
    ]
