# Generated by Django 4.2.7 on 2024-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0004_entree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entree',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
