# Generated by Django 4.2.7 on 2024-02-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0005_alter_entree_image_alter_entree_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
