# Generated by Django 4.2.7 on 2024-03-25 12:48

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0006_alter_entree_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images/gifs/'), upload_to='')),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pole.entree')),
            ],
        ),
    ]
