# Generated by Django 4.2.7 on 2024-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0007_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='image',
            field=models.ImageField(upload_to='media/gifs/'),
        ),
    ]
