# Generated by Django 4.2.7 on 2024-03-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0008_alter_gif_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='image',
            field=models.ImageField(upload_to='gifs/'),
        ),
    ]
