# Generated by Django 4.2.7 on 2024-03-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0009_alter_gif_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entree',
            name='image',
        ),
        migrations.AlterField(
            model_name='gif',
            name='image',
            field=models.FileField(upload_to='gifs/'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='pf',
            field=models.BooleanField(default=False, verbose_name='Pôle Féminin'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='ph',
            field=models.BooleanField(default=False, verbose_name='Pôle Masculin'),
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billet', models.FileField(upload_to='billets/')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pole.personne')),
            ],
        ),
    ]
