# Generated by Django 4.2.7 on 2024-04-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0010_remove_entree_image_alter_gif_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personne',
            options={'ordering': ['nom']},
        ),
        migrations.RemoveField(
            model_name='personne',
            name='carte',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='fin_validite',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='gare',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='mail',
        ),
        migrations.AlterField(
            model_name='personne',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
